---
- hosts: 172.31.3.117
  vars:
    falcon_client_id: 320D1BF101394DE9A098F939B4389BED-67
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_sensor_version_decrement: 1
  - role: crowdstrike.falcon.falcon_configure
